#+TITLE: Devlog
#+AUTHOR: Tyler Weldon
#+EMAIL: tylerweldon94@gmail.com

* <2020-09-26 Sat>
- Ansible provisioner porting from bash is mostly finished. Just a couple small things like a SystemD service for automatically starting KSP on deployment, and autoconfiguring the firewall to allow connections to the kRPC ports from the provisioning machine(Laptop, workstation, etc.). Adding functionality via the ansible config will be very much easier than stuffing more bash in here. Once those are done I'll initiate a build based on the new provisioner, at which point I think we'll be able to get some real work done.

  As we're running the game without graphics, we do need some kind of visuals. Initially I believe some combination of NASA's GMAT, and OpenMCT will do the trick. I'll begin by linking up:
  + Some misc. [[https://krpc.github.io/krpc/python/api/space-center/space-center.html][SpaceCenter]], [[https://krpc.github.io/krpc/python/api/space-center/comms.html][Comms]], [[https://krpc.github.io/krpc/python/api/space-center/parts.html][Parts]], [[https://krpc.github.io/krpc/python/api/space-center/reference-frame.html][ReferenceFrame]], and [[https://krpc.github.io/krpc/python/api/space-center/waypoints.html][Waypoints]] functions
  + Most of the [[https://krpc.github.io/krpc/python/api/space-center/vessel.html][Vessel]], [[https://krpc.github.io/krpc/python/api/space-center/vessel.html][CelestialBody]], [[https://krpc.github.io/krpc/python/api/space-center/flight.html][Flight]], [[https://krpc.github.io/krpc/python/api/space-center/orbit.html][Orbit]], and [[https://krpc.github.io/krpc/python/api/krpc/krpc.html][kRPC]] functions

  This should all give a pretty good picture of what is going on in the game so we can begin flying and experimenting with the Control and Flight functions.

* <2020-10-03 Sat>
- Another Saturday. I got the KSP systemd service and automatated opening the firewall for kRPC ports for connections from the controlling machine. Final image is built so we can start with the fun stuff, piping data into OpenMCT and GMAT. This will be roughly inspired by Telemachus and kerbal-openmct(both of which are quite outdated).

* <2020-11-17 Tue>
- Its been a while, life was pretty crazy the last 6 weeks and I haven't done anything for this. I've moved to Philadelphia, been her for almost a month now. Finally beginning to feel settled and can think clearly about side projects again. Today I rebuilt to the `astra-node` image and redeployed the terraform plan just to make sure everything works as I remember. I've reviewed this log and the README, lost my way with this a bit so had to reorient. Looks like we're at the point of needing to setup the kRPC streams(all of them). I think what I'll do is setup these streams in the backend server, then write an API around that which will be called by OpenMCT(javascript/jquery) - however it should be noted this will only be for observation and basic/non-critical controls. All flight control/automation will be done on the "flight" servers to minimize communication latency. Or rather, anything that would actually be done onboard would be done on the "flight" servers, and anything that would be done remotely will be done on the c2/OpenMCT node(s). So I'm realizing we might have 2 instances of OpenMCT, one "onboard" and one "remote" - since I think want to use OpenMCT as the flight  interface, heavily inspired by the new Crew Dragon touchscreen panel.

  Anyway. Next step in a sentance; backend data streams and astrctl cli(which will basically implement identical functionality to the OpenMCT C2, just entirely textual).


* <2021-01-21 Thu>
  - Well, almost exactly two months since last update and I've NOT DONE A SINGLE BIT OF WORK. Ugh. Holidays and general life craziness(Did 2020 ever really end...). I've also got a new primary dev machine, so will need to first ensure I can run all the build scripts and what not from here - then I can get back to data stream integration as above. WML!

    UPDATE: Ugh. I suppose I should update my terraform modules to use the Vultr Provider v2..and might as well restructure some of the project while I'm at it..picked up a few tricks since I started this.

* <2021-02-08 Mon>
- Just got off work and am going to go for a run. If afterwards I don't at least ensure I can download the Steam game, build the snapshot, and port everything to the Vultr TF Provider v2, someone open an issue on GH and call me a jabroni.

* <2021-02-09 Tue>
- Alright so I drank a /few/ beers and my ojectives changed. I got annoyed trying to port my build scripts over to my new machine, the slight nuances here and there, and decided instead of working on the TF stuff to move the build scripts over to github actions. At this point, I've got the game pulling/archiving/and uploading to s3 done. So thats nice. Next is to port the image build script over to GH Actions and the packer build over to the Vultr Packer plugin to v2...coulda swore I already did, will need to check my ThinkPad, it might be on there. In any case it is a small task. So in short I didn't get done what I'd originally planned, but got other equally helpful stuff done. You can still call me a jabroni or whatever but I'm just gonna keep drinking beers and chipping away at this.

  Update: Ok too many beers, gonna stop touching stuff. So what I'd originally set out to do yesterday(update the TF provider to Vultr v2) has already been done, and it is the updating Packer to the Vultr v2 plugin that still needs to be done... +yay+ cheers?

* <2021-02-12 Fri>
- Splitting the various Astra components(game build/archive, image build, terraform deployment module, etc.) into separate repos. Game builder repo is basically done. Will do packer image builder as part of updating packer to the Vultr v2 plugin. Need to do the actions script as well. Will be nice to not need to worry about local environment, the project should progress quite a bit faster with this automation in place.

  Update: Started this pretty much as soon as I got off work(4PM) and it is now 10:39PM. Strong day. The project organization is much better. Split out several repos:

  https://github.com/Oogy/packer-astra-flight
  https://github.com/Oogy/astra-ksp

  Next will be a separate repo for the Terraform module, and possibly the ansible plan. Maybe store a tar of the Ansible files as a release asset, pull it into the build similarly to https://github.com/Oogy/packer-astra-flight/blob/fe2cb345191f138a95901e7f0b1638892483c9af/.github/workflows/build.yml#L31. Time for a workout and sleep.


* <2021-02-13 Sat>
- Just continuing from yesterday. Got the TF module in its own repo. Also setup a Discord git webhook for the 3LA org.

* <2021-03-01 Mon>
- Life really do be like that sometimes, yk?
