#+TITLE: Devlog
#+AUTHOR: Tyler Weldon
#+EMAIL: tylerweldon94@gmail.com

* <2020-09-26 Sat>
- Ansible provisioner porting from bash is mostly finished. Just a couple small things like a SystemD service for automatically starting KSP on deployment, and autoconfiguring the firewall to allow connections to the kRPC ports from the provisioning machine(Laptop, workstation, etc.). Adding functionality via the ansible config will be very much easier than stuffing more bash in here. Once those are done I'll initiate a build based on the new provisioner, at which point I think we'll be able to get some real work done.

  As we're running the game without graphics, we do need some kind of visuals. Initially I believe some combination of NASA's GMAT, and OpenMCT will do the trick. I'll begin by linking up:
  + Some misc. [[https://krpc.github.io/krpc/python/api/space-center/space-center.html][SpaceCenter]], [[https://krpc.github.io/krpc/python/api/space-center/comms.html][Comms]], [[https://krpc.github.io/krpc/python/api/space-center/parts.html][Parts]], [[https://krpc.github.io/krpc/python/api/space-center/reference-frame.html][ReferenceFrame]], and [[https://krpc.github.io/krpc/python/api/space-center/waypoints.html][Waypoints]] functions
  + Most of the [[https://krpc.github.io/krpc/python/api/space-center/vessel.html][Vessel]], [[https://krpc.github.io/krpc/python/api/space-center/vessel.html][CelestialBody]], [[https://krpc.github.io/krpc/python/api/space-center/flight.html][Flight]], [[https://krpc.github.io/krpc/python/api/space-center/orbit.html][Orbit]], and [[https://krpc.github.io/krpc/python/api/krpc/krpc.html][kRPC]] functions

  This should all give a pretty good picture of what is going on in the game so we can begin flying and experimenting with the Control and Flight functions.

* <2020-10-03 Sat>
- Another Saturday. I got the KSP systemd service and automatated opening the firewall for kRPC ports for connections from the controlling machine. Final image is built so we can start with the fun stuff, piping data into OpenMCT and GMAT. This will be roughly inspired by Telemachus and kerbal-openmct(both of which are quite outdated).

* <2020-11-17 Tue>
- Its been a while, life was pretty crazy the last 6 weeks and I haven't done anything for this. I've moved to Philadelphia, been her for almost a month now. Finally beginning to feel settled and can think clearly about side projects again. Today I rebuilt to the `astra-node` image and redeployed the terraform plan just to make sure everything works as I remember. I've reviewed this log and the README, lost my way with this a bit so had to reorient. Looks like we're at the point of needing to setup the kRPC streams(all of them). I think what I'll do is setup these streams in the backend server, then write an API around that which will be called by OpenMCT(javascript/jquery) - however it should be noted this will only be for observation and basic/non-critical controls. All flight control/automation will be done on the "flight" servers to minimize communication latency. Or rather, anything that would actually be done onboard would be done on the "flight" servers, and anything that would be done remotely will be done on the c2/OpenMCT node(s). So I'm realizing we might have 2 instances of OpenMCT, one "onboard" and one "remote" - since I think want to use OpenMCT as the flight  interface, heavily inspired by the new Crew Dragon touchscreen panel.

  Anyway. Next step in a sentance; backend data streams and astrctl cli(which will basically implement identical functionality to the OpenMCT C2, just entirely textual).


* <2021-01-21 Thu>
  - Well, almost exactly two months since last update and I've NOT DONE A SINGLE BIT OF WORK. Ugh. Holidays and general life craziness(Did 2020 ever really end...). I've also got a new primary dev machine, so will need to first ensure I can run all the build scripts and what not from here - then I can get back to data stream integration as above. WML!

    UPDATE: Ugh. I suppose I should update my terraform modules to use the Vultr Provider v2..and might as well restructure some of the project while I'm at it..picked up a few tricks since I started this.
