- name: Create tmp dir for extract
  file:
    path: "{{ role_vars.alg_tmp_dir }}"
    state: directory
    mode: '0755'

- name: Get AutoLoadGame
  unarchive:
   src: "{{ autoloadgame_zip_url }}"
   remote_src: yes
   dest: "{{ role_vars.alg_tmp_dir }}"

- name: Install AutoLoadGame to game directory
  file:
    src: "{{ role_vars.alg_tmp_dir }}/GameData/AutoLoadGame"
    dest: "{{ ksp_install_dir }}/GameData"
    owner: "{{ game_user }}"
    group: "{{ game_user }}"
    remote_src: yes

- name: Configure AutoLoadGame for Astra
  file:
    src: files/AutoLoadGame.conf
    dest: "{{ ksp_install_dir }}/saves/AutoLoadGame.conf"
    owner: "{{ game_user }}"
    group: "{{ game_user }}"

- name: Cleanup
  file:
    path: "{{ role_vars.alg_tmp_dir }}"
    state: absent
