apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astra-ksp-storage
spec:
  storageClassName: shared-nvme-ord1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "50Gi"
