apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-flight
  labels:
    app.kubernetes.io/name: astra
    app.kubernetes.io/instance: release-name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: astra
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: astra
        app.kubernetes.io/instance: release-name
    spec:
      volumes:
        - name: astra-data
          persistentVolumeClaim:
            claimName: astra-ksp-storage
      containers:
        - name: astra-flight
          image: nvidia/cuda:11.7.1-runtime-ubuntu20.04
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
#          env:
#            - name:
#              value:
          resources:
            requests:
              cpu: 6
              memory: 32Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 6
              memory: 32Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: astra-data
              mountPath: /mnt/astra
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - ORD1
              - key: gpu.nvidia.com/class
                operator: In
                values:
                - RTX_A4000
