apiVersion: batch/v1
kind: Job
metadata:
  name: astra-mods-download
spec:
  template:
    spec:
      containers:
      - name: mods-downloader
        image: oogy/astra-mods:2
        imagePullPolicy: IfNotPresent
        command:
          - sleep
          - infinity
        volumeMounts:
          - name: game-storage
            mountPath: /mnt/astra
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
      volumes:
        - name: game-storage
          persistentVolumeClaim:
            claimName: astra-ksp-storage
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - ORD1
      restartPolicy: Never
  backoffLimit: 2