apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-flight
  labels:
    app.kubernetes.io/name: astra
    app.kubernetes.io/instance: release-name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: astra
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: astra
        app.kubernetes.io/instance: release-name
    spec:
      volumes:
        - name: astra-data
          persistentVolumeClaim:
            claimName: astra-ksp-storage
      containers:
        - name: astra-flight
          image: oogy/astra:alpha1
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
          env:
            - name: PUBLIC_KEY
              value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9yZlg7wYPxClZM5NumS8MonWPtuF85DasxbUBV9MUQVF7iDUBGmlnz2Cc5QZf5F27R5g+tm0CaghoT7V4FCH9AfuoslVR+8qtfCA2eCkJScQvBlUz1bhhtzqU8qH/tlcsZMaEj/NM+mo9OQYVUNx9nPghmUpVELIcOtxkPQn+YOS6kr6A10phf157HQcHgP91fgjMrncnCEYZhDq9+fRCNWGA6r3RZv683m3jFaYiS7sUDEGwIyFo/hc2HGpP/UTEbYOjHn+AyKCi5wK+9pPvCrFdiNcZrM6Y5FUiQLFLR9un9kczDhME2vLBkSU6FfuX1Ha6x8uqsZJK2cKIZNA4sn3xxti63I4UC/Q7CkJ8dLFFwA8wFq2RMnL19j1DvENI6dLLCRjPuqTTPcZmtoIaFdCCaRxD6CWL6c633NrMCzLQuvVkWU/AUYEUXTOjVVU3S1fl5nHGXo6ZwA3Ipxl6LTPFfipWv1A5/Y+yNJvhcSBH+bjGxuVuF/KmWatCS7tYXO4hdlELMlzcNdcjdFUlCGUf1fCgDOFaoViMFI1ccloCuxN9oNdWJFstU4DG6o6QInKDdELNqgJdAys6ExtSP0MbTnThJiKm5HVa7tII4bnJLWi7TUKhSILKwAwnkfCH121O846cB3st/GMR2hsFikUE98ra1K6G7pSYhaKMow== rucksack@deathnote"
          resources:
            requests:
              cpu: 12
              memory: 32Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 12
              memory: 32Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: astra-data
              mountPath: /mnt/astra
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - ORD1
              - key: gpu.nvidia.com/class
                operator: In
                values:
                - RTX_A4000
