name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  game-archiver:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Steam
        run: |
          sudo dpkg --add-architecture i386
          sudo apt -y update
          sudo apt -y install steamcmd
