name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  game-archiver:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Steam
        run: sudo apt -y install steamcmd
